name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Github SSH fingerprints
      run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts

    - name: Switch to Xcode 12.1
      run: sudo xcode-select --switch /Applications/Xcode_12.1.app

    # Compile project and run tests
    - name: Compile and run tests
      run: fastlane scan --scheme "Debug"

  build_release_prod:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Github SSH fingerprints
      run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts

    - name: Switch to Xcode 12.1
      run: sudo xcode-select --switch /Applications/Xcode_12.1.app
    
    # Compile "Release-Prod" for iOS Simulator (no signing)
    - name: Compile and run tests
      run: fastlane gym --scheme "Release-Prod" --skip_package_ipa true --destination "generic/platform=iOS Simulator"

  build_release_dev:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Github SSH fingerprints
      run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts

    - name: Switch to Xcode 12.1
      run: sudo xcode-select --switch /Applications/Xcode_12.1.app

    # Compile "Release-Dev" for iOS Simulator (no signing)
    - name: Compile and run tests
      run: fastlane gym --scheme "Release-Dev" --skip_package_ipa true --destination "generic/platform=iOS Simulator"
